apiVersion: v1
kind: Secret
metadata:
  name: transaction-consumer-secrets
  namespace: one-gate-payment
  labels:
    app: transaction-consumer
type: Opaque
stringData:
  brokers: "one-gate-payment-kafka-kafka-bootstrap:9092"
  topic: "transaction-events"
  group-id: "transaction-consumer-group"
  db-host: "postgresql-service"
  db-port: "5432"
  db-username: "developer"
  db-password: "developer123"
  db-name: "one_gate_payment"
